### ISSUE TITLE
implement PartialEq

### ISSUE THREAD

**Issue by happysalada** [rust-iso/rust_iso3166#2]
just a question, why is PartialEq not implemented for CountryCode, couldn't they be matched on their alpha2 representation ?
Am I missing something ?

**Comment by zhangjiayin** [comment]
Do you mean something like 
https://github.com/rust-iso/rust_iso3166/blob/main/src/bin/main.rs#L22-L36
cloud you check  that, and is it what you needed ?

**Comment by happysalada** [comment]
I was thinking of something like
```
impl PartialEq for CountryCode {
    fn eq(&self, other: &CountryCode) -> bool {
        self.0.alpha2 == other.0.alpha2
    }
}
```
Just so that you could compare 2 country codes together.

**Comment by zhangjiayin** [comment]
Could you create a Pull Request ?
