### ISSUE TITLE
Data pollution

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [rust-iso/rust_iso3166#6]
Some of the country names are polluted by Wikipedia footnotes. For example, Afghanistan and Cyprus have their English names listed by this library as `Afghanistan[b]` and `Cyprus[b]` due to a footnote linking to naming disputes.

**Comment by zhangjiayin** [comment]
Thank you for mention it.

it is fixed in https://github.com/rust-iso/rust_iso3166/commit/668eca69b3add8cb6f89e5a05035fa36cf7f2d5b
and https://crates.io/crates/rust_iso3166/0.1.10
