### ISSUE TITLE
Crate API changes based on platform

### ISSUE THREAD

**Issue by tazjin** [rust-iso/rust_iso3166#7]
For some reason, in WebAssembly builds the fields of `CountryCode` become private and instead have getter methods (so instead of `.name` you have to use `.name()`). I thought I was going crazy for a while because this is obviously not visible in the docs!

Is there a reason for this? This means that if the same code using this library is used in a wasm and a native application, it has to be feature gated to access fields in a different way, or do some kind of workaround with maybe a trait over the `CountryCode` field.

**Comment by tazjin** [comment]
Note that this also changes the type, i.e. on non-wasm architectures the field can be accessed as `&'static str`, but on wasm only as `String`, meaning that a platform-independent wrapper has to allocate on all platforms.

**Comment by zhangjiayin** [comment]
When we first started, we used &'static str to keep things simple. After supporting WASM, we also noticed the issues you mentioned. We've been trying to fix this problem while maintaining compatibility with older versions. If you have any good suggestions, please feel free to submit a PR. Thank you.

**Comment by zhangjiayin** [comment]
hi @tazjin 
 I've made a change to try to fix  this issue
could you try the branch  https://github.com/rust-iso/rust_iso3166/tree/fix-platform-api-bug

if it works well, I'll merge & publish it

**Comment by ocni-dtu** [comment]
Ran into the same issue. Is the branch still valid and can it be merged?

**Comment by zhangjiayin** [comment]
@ocni-dtu  it have been merged and published @0.1.13 
could you check it ?
